### PR TITLE
Fail throwing Error from custom rule

### LINKED ISSUE #20: Custom rules fail silently
If a custom rule fails (i.e. an error is thrown) the result will be ignored and as a result the rule will silently fail. It would be nice if svglint could report if a custom rule throws an error so that the user is aware something went wrong and doesn't think everything is fine.

### PR DESCRIPTION
**Pull request by mondeja**
Closes #20 

If you throw an `Error` from a custom rule is not reported, failing silently. I have used the `error` state in the absence of an `exception` state, but I'm not that familiar with the implementation as to define a new state because I'm not sure of the implications.

### CODE REVIEW

File: src/lib/linting.js [hunk 1]
```diff
@@ -171,14 +171,14 @@ class Linting extends EventEmitter {
         for (let k in this.results) {
             const result = this.results[k];
             if (result instanceof Array) {
-                if (result.some(res => res.hasErrors)) {
+                if (result.some(res => res.hasErrors) || result.some(res => res.hasExceptions)) {
```
Comment (birjolaxew) [inline src/lib/linting.js:174]: Probably best to use `result.some(res => res.hasErrors || res.hasExceptions)`, so we don't loop the array twice.

File: test/custom.spec.js [hunk 2]
```diff
@@ -111,6 +111,13 @@ describe("Rule: custom", function(){
             })
         ]);
     });
+    it("should fail with an exception inside function", function(){
```
Comment (birjolaxew) [inline test/custom.spec.js:114]: Could you fix the indentation here so the code linter passes?

**Review by birjolaxew — CHANGES_REQUESTED** [review]
Thanks for the quick PR!

I think using the `error` state is the right call. This means that the exception itself will be displayed as an exception ([using the `!!!` prefix](https://github.com/birjolaxew/svglint/blob/7ee1d8e69aa033d48f5c4856788cc0ba5bf023dd/src/cli/util.js#L36-L39)), while the file will be marked as errored. It's been a while since I've worked with svglint though, so it'd probably be best to manually test that this is the case.

I'm happy to merge and release after some minor changes.

**Comment by mondeja** [comment]
Changes done! :+1:

**Review by birjolaxew — APPROVED** [review]

**Comment by birjolaxew** [comment]
:+1: Thanks! I've quickly manually tested, and everything seems to be in order. I'll get this released asap.
